from src.utils.file_manager import FileManager
from src.answer.augmenting import Augmenting
from src.message.errors import AnswerError
from httpx import RemoteProtocolError
from ollama import chat, _types
from src.models.models import (
    MinimalAnswer,
    MinimalSource,
    StudentSearchResults
    )
from typing import Any
from tqdm import tqdm


class AnswerPipeline:
    """
    A pipeline capable of respond one or more requests based on source
    """
    @staticmethod
    def answer_generating_for_query(
        query: str,
        retrieved_sources: list[MinimalSource]
    ) -> Any:
        """Generate a response to a request from the selected source

        Args:
            query (str): The question we are going to answer
            retrieved_sources (list[MinimalSource]): The sources
            that were selected

        Returns:
            Any: The response generated by the model
        """
        model: str = "qwen3:0.6b"

        context = Augmenting(retrieved_sources).create_contexte(query)
        try:
            response = chat(
                model=model,
                messages=context,
                think=False,
                options={
                    "temperature": 0.2,
                    "num_ctx": 6000,
                    "num_predict": 512,
                    "num_batch": 2048,
                    },
            )
        except ConnectionError:
            raise AnswerError(
                "Please start ollama server with this command"
                "in another terminal: 'ollama serve'"
                )
        except RemoteProtocolError:
            raise AnswerError(
                "Please re-start ollama server with this command"
                "in another terminal: 'ollama serve'"
                )
        except _types.ResponseError:
            raise AnswerError(
                "Unknown model, download it first using the command"
                "'ollama pull qwen3:0.6b'"
            )
        return response["message"]["content"]

    def answer_generating_for_dataset(
        self,
        student_search_results_path: str,
        save_directory: str
    ) -> None:
        """
        Generate answers for a series of questions
        and save everything in a JSON file

        Args:
            student_search_results_path (str): Data paths derived from
            retrieving for all queries on a dataset
            save_directory (str): The path where the final JSON file
            will be saved
        """
        datas: StudentSearchResults = FileManager().load(
            student_search_results_path,
            StudentSearchResults
        )
        responses: list[MinimalAnswer] = []

        for data in tqdm(
            datas.search_results,
            desc=f"{"Answer":<15.15}",
            colour="cyan",
            unit="query",
            ascii="·■"
        ):

            sources = data.retrieved_sources

            responses.append(MinimalAnswer(
                question_id=data.question_id,
                question=data.question,
                retrieved_sources=sources,
                answer=self.answer_generating_for_query(
                    data.question,
                    sources
                )
            ))

        FileManager.write(
            [response.model_dump(mode="python") for response in responses],
            save_directory
        )
